### ISSUE TITLE
What are some of our favorite sites?

### ISSUE THREAD

**Issue by NateBatchelder** [NateBatchelder/cop-or-not#2]

**Comment by NateBatchelder** [comment]
Please feel free to add ideas of sites with unique functionality that you'd like to explore or are worthwhile 

1. Amazon 
- previously viewed
- suggested based on user
- suggested (trending)

2. Reddit 
- upvote
- awards
- public profile

**Comment by Connor-vb** [comment]
3. App Store 

 "App Previews" =  Guide to get through our website and how to use it properly. also displays our features
![IMG_0006](https://user-images.githubusercontent.com/90352499/146607899-0162a87c-67d9-46c6-addb-bbfb708b1a8f.jpeg)

**Comment by Blackcat-Tinkerngineers** [comment]
https://watch.screencastify.com/v/Khfpd0bYrOoZldAme2yZ

Steams drop down option to add wishlist etc
